name: Application build on GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gcp-production
    env:
      FINANCE_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/finance_service:latest
      BFF_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bff_service:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GCP authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SQL Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.13.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy ${{ secrets.GCP_DB_CONNECTION }} -p 5432 &

      - name: Verify db connection with psql
        run: |
          sudo apt-get install -y postgresql-client
          sleep 3
          psql "host=127.0.0.1 port=5432 user=postgres dbname=app-registry password=${{ secrets.GCP_DB_PW }}" -c "SELECT 1"

      - name: Authenticate Docker with GCR
        run: |
          gcloud auth configure-docker --quiet

      ## Build services
      - name: Build the Rust project
        run: |
          cargo build --release --workspace

      ## BUILD DOCKER FINANCE SERVICE
      - name: Build Docker finance_service image
        run: |
          docker build -t $FINANCE_IMAGE_NAME -f ./Dockerfile .

      - name: Push Docker finance_service image to GCR
        run: |
          docker push $FINANCE_IMAGE_NAME

      - name: Deploy finance_service to Cloud Run
        run: |
          gcloud run deploy finance-service \
            --image $FINANCE_IMAGE_NAME \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_USER }}

