name: Application build on GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gcp-production
    env:
      FINANCE_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/finance_service:latest
      BFF_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bff_service:latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: GCP authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
  
    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
  
    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker --quiet

    ## BUILD FINANCE SERVICE
    - name: Build Docker finance_service image
      run: |
        docker build -t $FINANCE_IMAGE_NAME -f ./services/finance/Dockerfile ./services/finance
  
    - name: Push Docker finance_service image to GCR
      run: |
        docker push $FINANCE_IMAGE_NAME

    - name: Deploy finance_service to Cloud Run
      run: |
        gcloud run deploy finance-service \
          --image $FINANCE_IMAGE_NAME \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${{ secrets.GCP_SA_USER }} \
          --set-env-vars PORT=${{ env.FINANCE_PORT }}

    ## BUILD BFF SERVICE
    - name: Build Docker bff_service image
      run: |
        docker build -t $BFF_IMAGE_NAME -f ./services/bff/Dockerfile ./services/bff
  
    - name: Push Docker bff_service image to GCR
      run: |
        docker push $BFF_IMAGE_NAME

    - name: Deploy bff_service to Cloud Run
      run: |
        gcloud run deploy bff-service \
          --image $BFF_IMAGE_NAME \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${{ secrets.GCP_SA_USER }} \
          --set-env-vars PORT=${{ env.BFF_PORT }}
